language: node_js
node_js:
  - "0.10"

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - bower install

script: 
  - node_modules/karma/bin/karma start karma.config.js --single-run

notifications:
  email:
    - demonchaux.stephane@gmail.com
